spring:
  config:
    import:
      - security/application-file.yml
      - security/application-jwt.yml
      - application-server.yml
      - application-test-datasource.yml
      - application-static-resources.yml
      - application-redis.yml