server:
  port: 7777
  servlet:
    session:
      tracking-modes: cookie

spring:
  config:
    import:
      - security/application-local-datasource.yml
      - security/application-jwt.yml

  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
        - classpath:/static/

file:
  dir: src/main/resources/static/images/arts/