version: "3"
services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - "../logs:/logs"
      - "./docker-configuration/promtail-prod.yml:/etc/promtail/config.yml"
    command: -config.file=/etc/promtail/config.yml
