version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "./docker-configuration/prometheus-prod.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: "$UID:$GID"
    ports:
      - "3000:3000"
    volumes:
      - "./docker-data/monitoring/grafana_data:/var/lib/grafana"
    depends_on:
      - prometheus
    privileged: true

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
